#!/bin/bash

BLACK_CKPT="L9/008/tb_logs/chess/version_6/last.pt2"
WHITE_CKPT="L9/007/tb_logs/chess/version_26/last.pt2"

cargo flamegraph --bin play -- \
  --white-device cuda --white-checkpoint $WHITE_CKPT \
  --black-type nn \
  --black-device cuda --black-checkpoint $BLACK_CKPT \
  -o tmp.json --rollout 300 --temperature 0 --cpuct 2.5
