#!/bin/bash
cargo flamegraph --bin play -- \
    --white-device cuda --white-checkpoint runs/21/tb_logs/chess/version_14/epoch-95.pt \
    --black-type nn \
    --black-device cuda --black-checkpoint runs/21/tb_logs/chess/version_14/epoch-95.pt \
    -o tmp.json --rollout 300 --temperature 0 --cpuct 2
