#!/bin/bash -eu

join() {
    local -n _array_to_print=$2
    local IFS=
    local _string_to_print="${_array_to_print[*]/#/"$1"}"
    echo "${_string_to_print/%"$1"}"
}

export ROOT=`cargo metadata --format-version 1 | jq -r ".workspace_root"`
export PYTHONPATH=$ROOT/py:$ROOT/target/release

cd $ROOT

LAST_=$(ls runs/ | sort -V -r | head -n 1)
CURR=${LAST:-$LAST_}
ITER=$(( $CURR + 1))
echo "Iteration $ITER"

mkdir -p runs/$ITER

if [ -z "$(ls | grep -E 'trace.+\.json')" ]; then
    echo "no trace files. I assume they have been moved already"
else
    mv trace*.json runs/$ITER/
fi

set -ex
pushd runs/$ITER
trace_files=( $(ls trace*.json) )
trace_args=$(join " -t " trace_files)
ckpt_file=$(find ../$CURR/tb_logs -name "*.ckpt" | sort -V | tail -n 1)
TRAIN_EPOCHS=${TRAIN_EPOCHS:-4}
python $ROOT/scripts/train.py $trace_args -n $TRAIN_EPOCHS -c $ckpt_file --lr 0.0001
popd

ckpt_file=$(find runs/$ITER/tb_logs -name "*.ckpt" | tail -n 1)
infer_args="-d cuda -n 150 --temperature 0.5 --cpuct 2"
scripts/run_batch $infer_args -r 8 --checkpoint $ckpt_file

set +ex
scripts/clean
# ls trace*.json
# ret=$?
# if [ $ret -gt 0 ]; then
#     scripts/run_batch $infer_args -r 6 --checkpoint $ckpt_file
#     scripts/clean
# fi
