#! /bin/bash

export ROOT=`cargo metadata --format-version 1 | jq -r ".workspace_root"`
export PYTHONPATH=${ROOT}/py
export PYTHON_SITE_PACKAGES=${ROOT}/venv/lib/python3.11/site-packages
export LD_LIBRARY_PATH=$PYTHON_SITE_PACKAGES/torch/lib:$PYTHON_SITE_PACKAGES/torch_tensorrt/lib:$PYTHON_SITE_PACKAGES/tensorrt_libs

task() {
    JOB_ID=$1
    ITER=$2
    VER=$3
    STEP=$4
    WHITE="runs/$ITER/tb_logs/chess/$VER/epoch-$STEP.pt"
    shift 4

    OUTPUT="${ITER}/${VER}_${STEP}"
    mkdir -p "replay/$ITER/${VER}_${STEP}"
    echo "Run index ${JOB_ID}: W: ${WHITE} B: ${BLACK} ARGS: $@" | tee "replay/$OUTPUT/meta"
    cargo r --release --bin play  -- \
        --white-device cuda --white-checkpoint $WHITE \
        --black-device cuda --black-type nn --black-checkpoint ${BLACK} \
        -o "${OUTPUT}/${JOB_ID}.json"\
        $@
}

export -f task

#set -ex
## export BLACK=''
## parallel -j3 task {#} 3 version_0 99 -d cuda --rollout=300 --temperature 0 --cpuct 1 ::: $(seq 1 100)
export BLACK="runs/25/tb_logs/chess/version_0/epoch-39.pt"
VARS=$(seq 1 100)
#parallel -j2 task {#} 26 version_0 55 --rollout=300 --temperature 0 --cpuct 2 ::: $VARS
#parallel -j2 task {#} 26 version_0 23 --rollout=300 --temperature 0 --cpuct 2 ::: $VARS
#parallel -j2 task {#} 26 version_0 79 --rollout=300 --temperature 0 --cpuct 2 ::: $VARS
#parallel -j2 task {#} 26 version_0 39 --rollout=300 --temperature 0 --cpuct 2 ::: $VARS
#parallel -j2 task {#} 26 version_0 71 --rollout=300 --temperature 0 --cpuct 2 ::: $VARS
parallel -j2 task {#} 26 version_0 7  --rollout=300 --temperature 0 --cpuct 2 ::: $VARS
parallel -j2 task {#} 26 version_0 15  --rollout=300 --temperature 0 --cpuct 2 ::: $VARS
