#! /bin/bash -eu

task() {
  JOB_ID=$1
  BASE=$2
  VER=$3
  WHITE="$BASE/$VER"
  shift 3

  echo "Run index ${JOB_ID}: W: ${WHITE} B: ${BLACK} ARGS: $@" | tee "replay/meta"
  cargo r --release --bin play -- \
    --white-device cuda --white-checkpoint $WHITE \
    --black-device cuda --black-checkpoint ${BLACK} \
    -o "replay/${JOB_ID}.json" \
    $@
}

export -f task

#set -ex
## export BLACK=''
## parallel -j3 task {#} 3 version_0 99 -d cuda --rollout=300 --temperature 0 --cpuct 1 ::: $(seq 1 100)
export BLACK="runs/017/tb_logs/chess/version_13/step:469-3.548-0.326.pt2"
export WHITEBASE="tb_logs/chess/version_3"
export WHITEVER="${WHITEVER:-step:1008-3.512-0.768.pt2}"

ROLLOUT=${ROLLOUT:-20}
TEMPERATURE=${TEMPERATURE:-0}
CPUCT=${CPUCT:-2.5}

mkdir -p "$PWD/replay"
rm -f $PWD/replay/*.json
echo "Results are saved in $PWD/replay"
parallel --linebuffer -j1 task {#} $WHITEBASE $WHITEVER --rollout=$ROLLOUT --temperature $TEMPERATURE --cpuct $CPUCT ::: $(seq 1 100)
