#! /bin/bash

export ROOT=`cargo metadata --format-version 1 | jq -r ".workspace_root"`
export PYTHONPATH=$ROOT/py


task() {
    JOB_ID=$1
    ITER=$2
    VER=$3
    STEP=$4
    WHITE="runs/$ITER/tb_logs/chess/$VER/epoch-$STEP.pt"
    shift 4

    OUTPUT="${ITER}/${VER}_${STEP}"
    mkdir -p "replay/$ITER/${VER}_${STEP}"
    echo "Run index ${JOB_ID}: W: ${WHITE} B: ${BLACK} ARGS: $@" | tee "replay/$OUTPUT/meta"
    cargo r --bin play --release -- \
        --white-checkpoint $WHITE --black-type nn --black-checkpoint ${BLACK}\
        -o "${OUTPUT}/${JOB_ID}.json"\
        $@
}

export -f task

set -ex
# export BLACK=''
# parallel -j3 task {#} 3 version_0 99 -d cuda --rollout=300 --temperature 0 --cpuct 1 ::: $(seq 1 100)
export BLACK="runs/10/tb_logs/chess/version_5/epoch-29.pt"
parallel -j2 task {#} 11 version_1 39 -d cuda --rollout=300 --temperature 0 --cpuct 3 ::: $(seq 1 100)