#! /bin/bash -eux

task() {
  JOB_ID=$1
  PREFIX=$2
  shift 2
  echo "Run index ${JOB_ID} using checkpoint ${W} ARGS $@"

  cargo r --bin play -- \
    --white-device ${DEVICE} --white-checkpoint ${W} \
    --black-type stockfish \
    -o "${PREFIX}${JOB_ID}.json" \
    $@
}

export -f task

export P=${P:-1}
export W="${W:-tb_logs/chess/version_0/last.pt2}"
export ROLLOUT=${ROLLOUT:-20}
export TEMPERATURE=${TEMPERATURE:-0}
export TEMPERATURE_SWITCH=${TEMPERATURE_SWITCH:-0}
export CPUCT=${CPUCT:-2.5}
export DEVICE=${DEVICE:-cuda}

rm -f replay/*.json
parallel --linebuffer -j${P} task {#} "replay/" --rollout=$ROLLOUT --temperature $TEMPERATURE --temperature-switch $TEMPERATURE_SWITCH --cpuct $CPUCT ::: $(seq 1 50)
DEST_PATH=replay/ ../scripts/show-result
